version: "3"
services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  api:
    build: ./api/
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
  front:
    build: ./front/
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd front && yarn start"
    ports:
      - "8000:3000"
    tty: true
    stdin_open: true
volumes:
  dbdata:
